"""Writes Resources/Prototypes/_WF/Asf/Roles/jobs.yml from the roster below.

Run from the repo root: python Tools/_WF/Asf/generate_roles.py
"""
from pathlib import Path

OUT = Path("Resources/Prototypes/_WF/Asf/Roles/jobs.yml")

# id, locale key, icon state, weight, overall playtime requirement (s), access group, extra equipment, backpack
JOBS = [
    ("Envoy", "envoy", "Envoy", 40, 72000, "WFAsfCommand",
     {"head": "WFAsfClothingHeadBeretPlumed", "outerClothing": "WFAsfClothingOuterGreatcoat",
      "neck": "WFAsfClothingNeckCapelet"},
     ["RadioHandheldNF", "WFAsfVoucherEscort"]),
    ("Enforcer", "enforcer", "Enforcer", 30, 36000, "WFAsfCrew",
     {"head": "WFAsfClothingHeadBeret", "outerClothing": "ClothingOuterArmorBasic", "pocket1": "WeaponDisabler"},
     ["RadioHandheldNF", "Handcuffs", "Handcuffs"]),
    ("FieldResearcher", "field-researcher", "Researcher", 20, 0, "WFAsfCrew",
     {"jumpsuit": "WFAsfClothingUniformResearcher", "outerClothing": "ClothingOuterCoatLab"},
     ["RadioHandheldNF", "HandheldHealthAnalyzer", "AnomalyScanner"]),
    ("Colonist", "colonist", "Colonist", 10, 0, "WFAsfCrew",
     {"jumpsuit": "WFAsfClothingUniformColonist", "belt": "ClothingBeltUtilityFilled",
      "gloves": "ClothingHandsGlovesColorYellow"},
     ["RadioHandheldNF"]),
]

LOADOUT_GROUPS = ["MercenaryBackpack", "ContractorNeck", "MercenaryGlasses", "ContractorBoxSurvival",
                  "ContractorWallet", "ContractorCartridge", "ContractorTrinkets", "ContractorBureaucracy"]


def job(jid, key, icon, weight, req, group, extra, storage):
    j = "WFAsf" + jid
    supervisors = "wf-asf-job-supervisors-council" if jid == "Envoy" else "wf-asf-job-supervisors-envoy"
    equipment = {"jumpsuit": "WFAsfClothingUniformService", "shoes": "WFAsfClothingShoesBoots",
                 "ears": "WFAsfClothingHeadset", "id": j + "PDA", **extra}
    lines = [
        "- type: job",
        f"  id: {j}",
        f"  name: wf-asf-job-{key}",
        f"  description: wf-asf-job-{key}-description",
        f"  playTimeTracker: Job{j}",
    ]
    if req:
        lines += ["  requirements:", "  - !type:OverallPlaytimeRequirement", f"    time: {req} # {req // 3600} hrs"]
    lines += [
        f"  startingGear: {j}Gear",
        "  alwaysUseSpawner: true",
        "  hideConsoleVisibility: true",
        f"  icon: JobIcon{j}",
        f"  supervisors: {supervisors}",
        "  assignedCompany: WFAsf",
        "  canBeAntag: false",
        f"  weight: {weight}",
        f"  displayWeight: {weight}",
        "  accessGroups:",
        "  - GeneralAccess",
        f"  - {group}",
        "",
        "- type: playTimeTracker",
        f"  id: Job{j}",
        "",
        "- type: startingGear",
        f"  id: {j}Gear",
        "  equipment:",
    ]
    lines += [f"    {slot}: {proto}" for slot, proto in equipment.items()]
    lines += ["  storage:", "    back:"] + [f"    - {s}" for s in storage]
    lines += ["", "- type: roleLoadout", f"  id: Job{j}", "  groups:"] + [f"  - {g}" for g in LOADOUT_GROUPS]
    lines += [
        "",
        "- type: jobIcon",
        "  parent: JobIcon",
        f"  id: JobIcon{j}",
        "  icon:",
        "    sprite: /Textures/_WF/Asf/Interface/job_icons.rsi",
        f"    state: {icon}",
        f"  jobName: wf-asf-job-{key}",
        "  allowSelection: false",
        "",
        "- type: entity",
        "  parent: IDCardStandard",
        f"  id: {j}IDCard",
        "  components:",
        "  - type: Sprite",
        "    layers:",
        "    - state: default",
        "    - state: idpassenger",
        "  - type: PresetIdCard",
        f"    job: {j}",
        "",
        "- type: entity",
        "  parent: BasePDA",
        f"  id: {j}PDA",
        "  components:",
        "  - type: Pda",
        f"    id: {j}IDCard",
        "  - type: PdaBorderColor",
        '    borderColor: "#7B52B8"',
        "",
        "- type: entity",
        "  parent: SpawnPointJobBase",
        f"  id: WFAsfSpawnPoint{jid}",
        "  components:",
        "  - type: SpawnPoint",
        f"    job_id: {j}",
        "  - type: Sprite",
        "    sprite: _WF/Asf/Structures/Banners/federation.rsi",
        "    state: asf-federation-banner",
        "",
    ]
    return "\n".join(lines)


header = "# Generated by Tools/_WF/Asf/generate_roles.py; edit the roster there.\n\n"
OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(header + "\n".join(job(*j) for j in JOBS), encoding="utf-8", newline="\n")
print("wrote", OUT)
